version: '3'
services:
  python:
    restart: always
    build: ./docker/python
    working_dir: '/root/src'
    tty: true
    volumes:
      - .:/root/src
    ports:
      - 9000:9000
    environment:
      - PORT=9000